### ISSUE TITLE
Divisibility testing is incorrect for Zn

### ISSUE THREAD

**Issue by byorgey** [disco-lang/disco#106]
For example:
```
Disco> (2 : Z7) divides (5 : Z7)
false
```
This should be `true`, since `(2 * 6 : Z7) = (5 : Z7)`.

**Comment by SanjitKal** [comment]
I think this bug is present because we don't have an OMDivides type for testing divisibility in mod spaces, so we just always desugar Divides operations regardless of their type to the ODivides type, which just uses a regular divisibility check assuming a mod space of 1. We can just create an OMDivides type, desugar Divides to OMDivides in the case of a finite type, and then use the modDiv operator to check if the two operands are divisible under the modspace.

**Comment by byorgey** [comment]
Yes, that sounds reasonable.
