### ISSUE TITLE
Add saturating subtraction operator for naturals/QP

### ISSUE THREAD

**Issue by byorgey** [disco-lang/disco#109]
Syntax `.-`?  Or `-.`?  Also allow Unicode ∸ .

Example:

```
> :type 3 .- 5
N
> :type 5.6 .- 8
QP
> 3 .- 5
0
> 5 .- 3
2
```

**Comment by byorgey** [comment]
Notice that `examples/grid.disco` currently does not load because subtraction on `N` no longer typechecks.  When we add this operator we should go back and update `grid.disco` to use it.

**Comment by byorgey** [comment]
As for the typing rule, the result type will just be the least upper bound of the two input types, and the result type must satisfy `QNum`.

**Comment by SanjitKal** [comment]
I commited  change which allows use of saturating subtraction operator. I also changed grid.disco to use it. However, I still get an error saying some program in the examples folder failed. I individually loaded each one (unless I missed one), and they all loaded fine. The only ones which obviously didn't load were the ones in the folders titled 'old' and 'ideas' (because they use type synonyms). I'm not sure what's going on.

**Comment by byorgey** [comment]
It looks like the one that was failing is `docs/tutorial/example/function.disco`.  The code included in the tutorial also gets checked by the test suite.  I pushed a fix just now.  The travis-ci build looks like it's failing for some other reason, I will look into it.

**Comment by byorgey** [comment]
We should also add a brief mention of saturating subtraction to the tutorial (*i.e.* wherever it talks about basic arithmetic operators).
